#!/bin/bash

if [ -f configure.ac.in ]; then
	CONFIGURE_AC=configure.ac.in
else
	CONFIGURE_AC=configure.ac
fi

test -f $CONFIGURE_AC || exit 1
test -f VERSION || exit 1

GETTEXT_PACKAGE=$(grep 'GETTEXT_PACKAGE=' $CONFIGURE_AC | cut -d= -f2)
PLUGIN_AUTHOR=$(grep 'PLUGIN_AUTHOR' $CONFIGURE_AC | cut -d\" -f2)
PLUGIN_ID=$(grep 'PLUGIN_ID' $CONFIGURE_AC | cut -d\" -f2)
PLUGIN_STATIC_NAME=$(grep 'PLUGIN_STATIC_NAME' $CONFIGURE_AC | cut -d\" -f2)
PLUGIN_WEBSITE=$(grep 'PLUGIN_WEBSITE' $CONFIGURE_AC | cut -d\" -f2)
PLUGIN_PREFS_PREFIX=$(grep 'PLUGIN_PREFS_PREFIX' $CONFIGURE_AC | cut -d\" -f2)
PLUGIN_VERSION=$(cat VERSION)


cat << EOF
/* Generated by scripts/gen_mingw_config_h.sh
 * from files VERSION and $CONFIGURE_AC.
 */
#define ENABLE_NLS 1
#define GETTEXT_PACKAGE "$GETTEXT_PACKAGE"
#define PLUGIN_AUTHOR "$PLUGIN_AUTHOR"
#define PLUGIN_ID "$PLUGIN_ID"
#define PLUGIN_STATIC_NAME "$PLUGIN_STATIC_NAME"
#define PLUGIN_VERSION "$PLUGIN_VERSION"
#define PLUGIN_WEBSITE "$PLUGIN_WEBSITE"
#define PLUGIN_PREFS_PREFIX "$PLUGIN_PREFS_PREFIX"
EOF
